### ISSUE TITLE
support import from Freetube exports: subscriptions, history, playlists

### ISSUE THREAD

**Issue by yoguut** [libre-tube/LibreTube#3677]
### Describe your suggested feature

Currently importing from Freetube data is not supported, although Freetube can export subscription for Newpipe format and then allows LibreTube to import such subscription successfully as a workaround.

There are no workaround for the other 2 feature for importing Freetube data: history and playlists.

To add support for these 3 features, I propose to follow the similar UI flow from FreeTube:
1. Prompt the user which format to import from (so that we can build a more deterministic parsing logic for the data format. This way we can prevent & isolate potential issues in the future if Newpipe or Freetube decided to update their data format)
2. Trim unnecessary data (such as `"_id": "xcmrX4RAO1IOj2Mr"` from FreeTube's playlists. Tbh, idk what this id do for the Freetube client, if anyone knows more, pls provide context)
3. Persist data into LibreTube client

### Other details

related to discussion from #3675 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Tasks

- [x] create enum to encapsulate types of supported clients
- [x] impl alert dialog on ui                                                    
- [ ] translate "Import from"                                                    
- [x] add serializable classes for freetube, libretube, newpipe                 
- [ ] test parsing logic

**Comment by FireMasterK** [comment]
> _id would be used by FreeTube mainly for when support for multiple playlists is added to FreeTube.

I fail to understand what that is, is that a playlist id of some sort?

**Comment by ChunkyProgrammer** [comment]
> > _id would be used by FreeTube mainly for when support for multiple playlists is added to FreeTube.
> 
> I fail to understand what that is, is that a playlist id of some sort?

Yep, it's just the playlist id 🙂

**Comment by yoguut** [comment]
> > _id would be used by FreeTube mainly for when support for multiple playlists is added to FreeTube.
> 
> I fail to understand what that is, is that a playlist id of some sort?

i don't see FreeTube's linux client has support for multiple playlists. but having the notion of unique `_id` per playlist seems smart and future proof it for potential UI enhancement... i will try to consider it too if i get better at writing codes in kt :)
